[package]
name = "precop_layout"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Layout cops for PreCop"

[dependencies]
precop_core.workspace = true
precop_ast.workspace = true
