[package]
name = "precop_ast"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "AST utilities for PreCop"

[dependencies]
ruby-prism.workspace = true
